name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: root
          POSTGRES_DB: dbtci_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install package
      run: |
        pip install -e .[test]
    - name: Lint with black
      run: |
        black . --check
    - name: Test with pytest
      env:
        CI_DBT_USER: root
        CI_DBT_PASS: postgres
        CI_DBT_PORT: 5432
        CI_DBT_DBNAME: dbtci_test
      run: |
        mkdir -p ~/.dbt
        cd tests/integration
        cp ci/sample_profiles.yml ~/.dbt/profiles.yml
        mkdir -p models
        dbt deps
        pytest -v --cov-report= --cov dbtci
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      run: |
        pip install setuptools wheel twine
        python setup.py sdist bdist_wheel
        python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*

