name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install package
      run: |
        pip install -e .[test]
    - name: Lint with black
      run: |
        black . --check
    - name: Test with pytest
      env:
        CI_DBT_USER: root
        CI_DBT_PASS: ''
        CI_DBT_PORT: 5432
        CI_DBT_DBNAME: dbtci_test
      run: |
        mkdir -p ~/.dbt
        cp tests/integration/ci/sample_profiles.yml ~/.dbt/profiles.yml
        mkdir -p tests/integration/models
        pytest -v --cov-report= --cov dbtci
        coverage combine .coverage
        coverage report
        coverage html
        pytest tests/integration
        pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
